/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 08 01:09:08 GMT 2020
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.mooctest.Othello;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Othello_ESTest extends Othello_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Othello othello0 = new Othello();
      String[][] stringArray0 = new String[5][6];
      // Undeclared exception!
      try { 
        othello0.strategyOfBlackMove(stringArray0, stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 6
         //
         verifyException("net.mooctest.Othello", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Othello othello0 = new Othello();
      String[][] stringArray0 = new String[1][6];
      String[] stringArray1 = new String[6];
      stringArray1[5] = "*";
      stringArray0[0] = stringArray1;
      // Undeclared exception!
      try { 
        othello0.strategyOfBlackMove(stringArray0, stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 6
         //
         verifyException("net.mooctest.Othello", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Othello othello0 = new Othello();
      // Undeclared exception!
      try { 
        othello0.strategyOfBlackMove((String[][]) null, (String[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Othello", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Othello othello0 = new Othello();
      String[][] stringArray0 = new String[5][6];
      String[][] stringArray1 = new String[9][9];
      // Undeclared exception!
      try { 
        othello0.strategyOfBlackMove(stringArray1, stringArray0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
